apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ivip-kibana
  name: ivip-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivip-kibana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ivip-kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.6.2
        name: kibana
        resources: {}
status: {}
