apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ivip-kibana
  name: ivip-kibana
spec:
  ports:
  - name: 5601-5601
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: ivip-kibana
  type: ClusterIP
status:
  loadBalancer: {}
