apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ivip-keycloak
  name: ivip-keycloak
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8180-8180
    port: 8180
    protocol: TCP
    targetPort: 8180
  selector:
    app: ivip-keycloak
  type: ClusterIP
status:
  loadBalancer: {}
