version: '3.8'
services:
    ivip-pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@localhost.localdomain
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - 15080:80
        networks:
          - ${GLOBAL_NETWORK:-application}
    ivip-keycloak:
        image: jboss/keycloak:${KEYCLOAK_VERSION:-11.0.2}
        ports:
          - 16080:8080
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        networks:
          - ${GLOBAL_NETWORK:-application}
    ivip-nexus:
        image: sonatype/nexus3
        ports:
          - 15081:8081
        networks:
          - ${GLOBAL_NETWORK:-application}
    ivip-postgres:
        image: postgres:${POSTGRESQL_VERSION:-14.1}
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        networks:
          - ${GLOBAL_NETWORK:-application}
    ivip-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-7.9.3}
        ports:
          - 9200:9200
        environment:
            discovery.type: single-node
        networks:
          - ${GLOBAL_NETWORK:-application}
    ivip-kibana: 
        image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION:-7.9.3}
        environment:
            ELASTICSEARCH_HOSTS: http://ivip-elasticsearch:9200
        ports:
          - 5601:5601
        restart: on-failure
        depends_on:
          - ivip-elasticsearch
        networks:
          - ${GLOBAL_NETWORK:-application}
    filebeat:
        image: docker.elastic.co/beats/filebeat:${ELASTICSEARCH_VERSION:-7.9.3}
        volumes:
            - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro 
            - /var/lib/docker/containers:/var/lib/docker/containers:ro          
            - /var/run/docker.sock:/var/run/docker.sock:ro                      
        user: root                                                              
        restart: on-failure
        depends_on:
          - ivip-elasticsearch
        networks:
          - ${GLOBAL_NETWORK:-application}
    zookeeper:
        image: confluentinc/cp-zookeeper:${KAFKA_VERSION:-5.0.4}
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        ports:
          - 22181:2181
        networks:
        - ${GLOBAL_NETWORK:-application}
    schema-registry:
        image: confluentinc/cp-schema-registry:${KAFKA_VERSION:-5.0.4}
        hostname: schema-registry
        depends_on:
          - zookeeper
          - kafka-broker-1
          - kafka-broker-2
          - kafka-broker-3
        ports:
          - 8081:8081
        environment:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
          SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
          SCHEMA_REGISTRY_DEBUG: 'true'
        networks:
          - ${GLOBAL_NETWORK:-application}
    kafka-broker-1:
      image: confluentinc/cp-kafka:${KAFKA_VERSION:-5.0.4}
      hostname: kafka-broker-1
      ports:
        - 19092:19092
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-application}
    kafka-broker-2:
      image: confluentinc/cp-kafka:${KAFKA_VERSION:-5.0.4}
      hostname: kafka-broker-2
      ports:
        - 29092:29092
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-application}
    kafka-broker-3:
      image: confluentinc/cp-kafka:${KAFKA_VERSION:-5.0.4}
      hostname: kafka-broker-3
      ports:
        - 39092:39092
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 3
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_COMPRESSION_TYPE: producer
      networks:
        - ${GLOBAL_NETWORK:-application}
