apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivip-kafka
spec:
  selector:
    matchLabels:
      app: ivip-kafka
  template:
    metadata:
      labels:
        app: ivip-kafka
    spec:
      containers:

      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: 'schema-registry'
          - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
            value: 'zookeeper:2181'
          - name: SCHEMA_REGISTRY_LISTENERS
            value: 'http://schema-registry:8081'
          - name: SCHEMA_REGISTRY_DEBUG
            value: 'true'
        
      - name: kafka-broker-1
        image: confluentinc/cp-kafka:5.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
          - name: KAFKA_BROKER_ID
            value: '1'
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 'zookeeper:2181'
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
      - name: kafka-broker-2
        image: confluentinc/cp-kafka:5.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
          - name: KAFKA_BROKER_ID
            value: '2'
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 'zookeeper:2181'
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
      - name: kafka-broker-3
        image: confluentinc/cp-kafka:5.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
          - name: KAFKA_BROKER_ID
            value: '3'
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 'zookeeper:2181'
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
