apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ivip-web-auth
  name: ivip-web-auth
spec:
  ports:
  - name: 8091-8091
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: ivip-web-auth
  type: ClusterIP
status:
  loadBalancer: {}
