apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivip-neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivip-neo4j
  strategy: {}
  template:
    metadata:
      labels:
        app: ivip-neo4j
    spec:
      containers:
      - image: neo4j:4.3.6
        name: neo4j
        resources: {}
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-secrets
              key: NEO4J_AUTH
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          valueFrom:
            secretKeyRef:
              name: neo4j-secrets
              key: NEO4J_ACCEPT_LICENSE_AGREEMENT
        volumeMounts:
        - name: data
          mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ivip-neo4j-data
