apiVersion: v1
kind: Service
metadata:
  name: ivip-neo4j
  labels:
    app: ivip-neo4j
spec:
  type: ClusterIP
  selector:
    app: ivip-neo4j
  ports:
  - name: http
    port: 7474
    targetPort: 7474
  - name: bolt
    port: 7687
    targetPort: 7687