apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ivip-elasticsearch
  name: ivip-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivip-elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ivip-elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        name: elascticsearch
        resources: {}
        env:
        - name: discovery.type
          value: single-node
status: {}
