apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ivip-elasticsearch
  name: ivip-elasticsearch
spec:
  ports:
  - name: 9200-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: ivip-elasticsearch
  type: ClusterIP
status:
  loadBalancer: {}
